# list users
GET http://localhost:3333/users

###
# create user
POST http://localhost:3333/users
Content-Type: application/json

{
    "name": "Lucas S. Corte",
    "email": "andressa@corte.tech"
}

###
# update user
PUT http://localhost:3333/users/ad49070b-b337-4a09-b6cb-e5dd230f5122
Content-Type: application/json

{
    "name": "Lucas S. Corte",
    "email": "lucas@corte.tech"
}

###
# delete user
DELETE http://localhost:3333/users/a20c46bf-2d52-4c44-8988-d91ac38dc56d