@baseURL = http://localhost:3333

###
# @name createTransaction
POST {{baseURL}}/transactions
Content-Type: application/json

{
	"title": "Aluguel",
	"amount": 400,
	"type": "debit"
}

###
# @name listAllTransaction
GET {{baseURL}}/transactions HTTP/1.1

###
# @name listTransactionById
GET {{baseURL}}/transactions/e87cd985-b417-43d8-b562-4ec94ae05aa0 HTTP/1.1

###
# @name summaryTransactions
GET {{baseURL}}/transactions/summary HTTP/1.1