@baseURL = http://localhost:3333

# @name getAllUsers
GET {{baseURL}}/users HTTP/1.1

###
# @name getUsersByFilter
GET {{baseURL}}/users?search=LUCAS HTTP/1.1

###
# @name createNewUser
POST {{baseURL}}/users HTTP/1.1
Content-Type: application/json

{
  "name": "Lucas Corte",
  "email": "cortelucas@example.com"
}

###
# @name updateNewUser
PUT {{baseURL}}/users/2ca76eb0-6478-49d0-9ca0-42caee5cdc8e HTTP/1.1
Content-Type: application/json

{
  "name": "Lucas Corte",
  "email": "lucas.corte@example.com"
}

###
# @name deleteUser
DELETE {{baseURL}}/users/b78f14fd-0e10-4404-8aa8-a66259af9813 HTTP/1.1